export const GET_DATA_LOADING = "GET_DATA_LOADING";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_ERROR = "GET_DATA_SUCCESS";

export const PRODUCT_SEARCH = "PRODUCT_SEARCH";
export const PRODUCT_FILTER = "PRODUCT_FILTER";